version: '3.8'

volumes:
  postgres_db: {}
  redis_db: {}

networks:
  bridge:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=usedeall
      - POSTGRES_PASSWORD=irvankdhf
      - POSTGRES_DB=user-service
    volumes:
      - "postgres_db:/var/lib/postgresql/data"
    stdin_open: true
    networks:
      - bridge
    ports:
      - "25432:5432"
  redis:
    image: redis:5.0
    networks:
      - bridge
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "16379:6379"
    volumes:
      - "redis_db:/data"