version: '3.8'

volumes:
  postgres_db: {}

networks:
  bridge:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=usedeall
      - POSTGRES_PASSWORD=irvankdhf
      - POSTGRES_DB=user-service
    volumes:
      - "postgres_db:/var/lib/postgresql/data"
    stdin_open: true
    networks:
      - bridge
    ports:
      - "25432:5432"

#services:
#  mongodb:
#    image: mongo:6.0
#    volumes:
#      - mongodb_data:/data/db
#    ports:
#      - "27017:27017"
#
#volumes:
#  mongodb_data: